/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.businessprofit.panels;

import java.awt.BorderLayout;
import java.util.Date;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author sotir
 */
public class DatePicker extends javax.swing.JPanel {
    private JXDatePicker picker;
    /**
     * Creates new form DatePicker
     */
    public DatePicker() {
        initComponents();
        
        picker = new JXDatePicker(new Date());
        this.add(picker, BorderLayout.CENTER);
    }
    public Date getDate() {
        return this.picker.getDate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
