
package org.riflemansd.businessprofit.main;

import java.awt.FlowLayout;
import javax.swing.JOptionPane;
import org.riflemansd.businessprofit.MyItemListener;
import org.riflemansd.businessprofit2.Category;
import org.riflemansd.businessprofit2.IncomeCost;
import org.riflemansd.businessprofit2.PackagesIncome;

/**
 *
 * @author rifleman
 */
public class InsertForm extends javax.swing.JFrame {
    private String[] categorys;
    /** Creates new form InsertForm */
    public InsertForm() {
        this.setBounds(100, 100, 1000, 1000);
        
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        
        
        categorys = BusinessProfit.database.getCategorys().split("\n");
        
        categoryJCB.removeAllItems();
        for (String cat : categorys) {
            categoryJCB.addItem(cat.split(",")[1]);
        }
        categoryJCB.addItemListener(new MyItemListener(this));
        
        esodoeksodoJCB.removeAllItems();
        esodoeksodoJCB.addItem("Έσοδο");
        esodoeksodoJCB.addItem("Έξοδο");
        
        esodoeksodoJCB.addItemListener(new MyItemListener(this));
        
        centerPanel.setLayout(new FlowLayout(1));
        if (categoryJCB.getSelectedItem().equals("Δέματα")) {
            centerPanel.add(new InsertPanelPackages());
        }
        else {
            centerPanel.add(new InsertPanel());
        }
        
        //revalidate();
        //repaint();
        
        this.setLocationRelativeTo(null);
    }

    public void setInsertPanel() {
        centerPanel.removeAll();
        
        if (categoryJCB.getSelectedItem().equals("Δέματα") && esodoeksodoJCB.getSelectedIndex() == 0) {
            centerPanel.add(new InsertPanelPackages());
        }
        else {
            centerPanel.add(new InsertPanel());
        }
        
        revalidate();
        repaint();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        categoryJCB = new javax.swing.JComboBox();
        esodoeksodoJCB = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        insertButton.setText("Εισαγωγή");
        insertButton.setHideActionText(true);
        insertButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insertButton.setPreferredSize(new java.awt.Dimension(80, 100));
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        jPanel1.add(insertButton, java.awt.BorderLayout.PAGE_END);

        centerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        centerPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        centerPanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(centerPanel, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Κατηγορία");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Έσοδο/Έξοδο");

        categoryJCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryJCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryJCBActionPerformed(evt);
            }
        });

        esodoeksodoJCB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        esodoeksodoJCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Έσοδο", "Έξοδο" }));
        esodoeksodoJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esodoeksodoJCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(esodoeksodoJCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esodoeksodoJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jPanel1.add(HeaderPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        String item = (String)categoryJCB.getSelectedItem();
        Category cat = BusinessProfit.database.getCategory(item);
        int index = esodoeksodoJCB.getSelectedIndex();
        
        if (item.equals("Δέματα") && index == 0) {
            InsertPanelPackages p = (InsertPanelPackages)centerPanel.getComponent(0);
            
            String aitiologia = p.getAitiologia();
            int paradoseis = p.getParadoseis();
            int paralabes = p.getParalabes();
            
            if (paradoseis == -1 || paralabes == -1) {
                JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αποθήκευση!","Αποτυχία",JOptionPane.ERROR_MESSAGE);
            }
            else {
                System.out.println(aitiologia + " " + paradoseis + " " + paralabes);
                BusinessProfit.database.savePackIn(new PackagesIncome(0, cat, aitiologia, paradoseis, paralabes), p.getDate());
                JOptionPane.showMessageDialog(this, "Τα δεδομένα αποθηκεύτηκαν!","Επιτυχία",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else {
            if (index == 0) {
                InsertPanel p = (InsertPanel)centerPanel.getComponent(0);

                String aitiologia = p.getAitiologia();
                double poso = p.getPoso();

                if (poso == -1) {
                    JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αποθήκευση!","Αποτυχία",JOptionPane.ERROR_MESSAGE);
                }
                else {
                    System.out.println(aitiologia + " " + poso);
                    BusinessProfit.database.saveIn(new IncomeCost(0, cat, aitiologia, poso), p.getDate());
                    JOptionPane.showMessageDialog(this, "Τα δεδομένα αποθηκεύτηκαν!","Επιτυχία",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else if (index == 1) {
                InsertPanel p = (InsertPanel)centerPanel.getComponent(0);

                String aitiologia = p.getAitiologia();
                double poso = p.getPoso();

                if (poso == -1) {
                    JOptionPane.showMessageDialog(this, "Δεν είναι δυνατή η αποθήκευση!","Αποτυχία",JOptionPane.ERROR_MESSAGE);
                }
                else {
                    System.out.println(aitiologia + " " + poso);
                    BusinessProfit.database.saveOut(new IncomeCost(0, cat, aitiologia, poso), p.getDate());
                    JOptionPane.showMessageDialog(this, "Τα δεδομένα αποθηκεύτηκαν!","Επιτυχία",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_insertButtonActionPerformed

    private void esodoeksodoJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esodoeksodoJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esodoeksodoJCBActionPerformed

    private void categoryJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryJCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JComboBox categoryJCB;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox esodoeksodoJCB;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
