/* ~~ ﻿The ResaultPanel is part of BusinessProfit. ~~
 * 
 * The BusinessProfit's classes and any part of the code 
 * cannot be copied/distributed without 
 * the permission of Sotiris Doudis
 * 
 * Github - RiflemanSD - https://github.com/RiflemanSD
 * 
 * Copyright © 2016 Sotiris Doudis | All rights reserved
 * 
 * License for BusinessProfit project - in GREEK language
 * 
 * Οποιοσδήποτε μπορεί να χρησιμοποιήσει το πρόγραμμα για προσωπική του χρήση. 
 * Αλλά απαγoρεύεται η πώληση ή διακίνηση του προγράμματος σε τρίτους.
 * 
 * Aπαγορεύεται η αντιγραφή ή διακίνηση οποιοδήποτε μέρος του κώδικα χωρίς 
 * την άδεια του δημιουργού. 
 * Σε περίπτωση που θέλετε να χρεισημοποιήσετε κάποια κλάση ή μέρος του κώδικα.
 * Πρέπει να συμπεριλάβεται στο header της κλάσης τον δημιουργό και link στην
 * αυθεντική κλάση (στο github).
 * 
 * ~~ ﻿Information about BusinessProfit project - in GREEK language ~~
 *  
 * Το BusinessProfit είναι ένα project για την αποθήκευση και επεξεργασία
 * των εσόδων/εξόδων μίας επιχείρησης με σκοπό να μπορεί ο επιχειρηματίας να καθορήσει 
 * το καθαρό κέρδος της επιχείρησης. Καθώς και να κρατάει κάποια σημαντικά
 * στατιστικά στοιχεία για τον όγκο της εργασίας κτλ..
 *  
 * Το project δημιουργήθηκε από τον Σωτήρη Δούδη. Φοιτητή πληροφορικής του Α.Π.Θ
 * για προσωπική χρήση. Αλλά και για όποιον άλλον πιθανόν το χρειαστεί.
 * 
 * Το project προγραμματίστηκε σε Java (https://www.java.com/en/download/).
 * Με χρήση του NetBeans IDE (https://netbeans.org/)
 * Για να το τρέξετε πρέπει να έχετε εγκαταστήσει την java.
 *  
 * Ο καθένας μπορεί δωρεάν να χρησιμοποιήσει το project αυτό. Αλλά δεν επιτρέπεται
 * η αντιγραφή/διακήνηση του κώδικα, χωρίς την άδεια του Δημιουργού (Δείτε την License).
 * 
 * Github - https://github.com/RiflemanSD/BusinessProfit
 * 
 * 
 * Copyright © 2016 Sotiris Doudis | All rights reserved
 */
package org.riflemansd.businessprofit.main;

import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;


/** <h1>﻿ResaultPanel</h1>
 * 
 * <p></p>
 * 
 * <p>Last Update: 28/01/2016</p>
 * <p>Author: <a href=https://github.com/RiflemanSD>RiflemanSD</a></p>
 * 
 * <p>Copyright © 2016 Sotiris Doudis | All rights reserved</p>
 * 
 * @version 1.0.7
 * @author RiflemanSD
 */
public class ResaultPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ResaultPanel
     */
    public ResaultPanel() {
        initComponents();
        
        this.setBackground(new Color(255, 245, 108));
    }

    public void updateProfit(double income, double costs) {
        double profit = income - costs;
        
        profit = round(profit, 3);
        income = round(income, 3);
        costs = round(costs, 3);
        
        if (profit <= 0) {
            this.calcLabel.setText("<html>   <font color='blue'>"+income+"</font> + <font color='orange'>"+costs+"</font> = <font color='red'>"+profit+"</font> €</html>");
        }
        else {
            this.calcLabel.setText("<html>   <font color='blue'>"+income+"</font> + <font color='orange'>"+costs+"</font> = <font color='#00FF00'>"+profit+"</font> €</html>");
        }
    }
    
    private double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();

        BigDecimal bd = new BigDecimal(value);
        bd = bd.setScale(places, RoundingMode.HALF_UP);
        return bd.doubleValue();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profitTextLabel = new javax.swing.JLabel();
        calcLabel = new javax.swing.JLabel();

        profitTextLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        profitTextLabel.setText("Καθαρό Κέρδος:  ");
        add(profitTextLabel);

        calcLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calcLabel.setText("400 - 320 = 80 €");
        add(calcLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcLabel;
    private javax.swing.JLabel profitTextLabel;
    // End of variables declaration//GEN-END:variables
}
