/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.riflemansd.businessprofit.main;

import java.awt.Color;

/**
 *
 * @author RiflemanSD
 */
public class ResaultPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form ResaultPanel
     */
    public ResaultPanel() {
        initComponents();
        
        this.setBackground(new Color(255, 245, 108));
    }

    public void updateProfit(double income, double costs) {
        double profit = income - costs;
        
        if (profit <= 0) {
            this.calcLabel.setText("<html>   <font color='blue'>"+income+"</font> + <font color='orange'>"+costs+"</font> = <font color='red'>"+profit+"</font> €</html>");
        }
        else {
            this.calcLabel.setText("<html>   <font color='blue'>"+income+"</font> + <font color='orange'>"+costs+"</font> = <font color='#00FF00'>"+profit+"</font> €</html>");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profitTextLabel = new javax.swing.JLabel();
        calcLabel = new javax.swing.JLabel();

        profitTextLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        profitTextLabel.setText("Καθαρό Κέρδος:  ");
        add(profitTextLabel);

        calcLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        calcLabel.setText("400 - 320 = 80 €");
        add(calcLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calcLabel;
    private javax.swing.JLabel profitTextLabel;
    // End of variables declaration//GEN-END:variables
}
